# Input method
exec-once = fcitx5

# Core components (authentication, lock screen, notification daemon)
# exec-once = dbus-update-activation-environment --all &
# exec-once = /usr/bin/gnome-keyring-daemon --start --components=secrets &
# exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# exec-once = sleep 1 && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP # Some fix idk


exec-once = nm-applet
exec-once = blueman-applet
exec-once = clipse --listen
exec-once = nwg-drawer -r -ovl

exec-once = way-edges --config-path ~/.config/way-edges/hyprland.jsonc
exec-once = qs -c noctalia-shell


exec-once =  hyprpm reload
